blog/api/urls.py
from django.urls import path

from .views import LikeToggleAPIView

urlpatterns = [
    path('<int:pk>/like/', LikeToggleAPIView.as_view(), name='like_api')
]

blog/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    add_comment
)

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    # path('videos',views.VideoListView.as_view(),name='videos'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user_posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', views.update_post, name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('about/', views.about, name='about'),
    path('post/<int:pk>/comment/', add_comment, name='add_comment')
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # API urls
    path('api-blog/', include('blog.api.urls')),
    # Blog urls
    path('', include('blog.urls')),
    # Authentication Urls
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    # Resete Password Urls
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    # Change Password Urls
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='users/password_change.html'), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    path('', include('blog.urls')),

blog/forms.py
from pyexpat import model
from django import forms 

from .models import Post
from django.forms import DateTimeInput




class ChoicesForm(forms.Form):
    POST_CHOICES = (
    (0,'---'),    
    (1,'Show'),
    (2,'Talent'),
    (3,'Event/Festival'),
    (4,'Rent'),
    (5,'Contact'),

    
    )
    post_select = forms.ChoiceField(choices=POST_CHOICES)


class ShowForm(forms.ModelForm):
    class Meta:
        model = Post
        widgets = {
                
                'description': forms.Textarea(attrs={
                    'cols': 20, 
                    'rows': 3
                }),
        }
        fields = ['name', 'show', 'video_link','img', 'show_language','genre','description','tags']
      
    
    def __init__(self, *args, **kwargs):
        super(ShowForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Movie Name"
        self.fields['show_language'].label = "Language"
        self.fields['img'].label ="Poster"
        self.fields['tags'].label = "#Tags"

class TalentForm(forms.ModelForm):
    class Meta:
        model=Post
        widgets = {
                
                'description': forms.Textarea(attrs={
                    'cols': 20, 
                    'rows': 3
                }),
        }
        fields=['name','talent','language','location','img','description','tags']
    def __init__(self, *args, **kwargs):
        super(TalentForm, self).__init__(*args, **kwargs)
        self.fields['img'].label ="Photo"
        self.fields['tags'].label = "#Tags"
        

class EventForm(forms.ModelForm):
    class Meta:
        model = Post
        widgets = {
                'From': DateTimeInput(attrs={
                   
                'type': "datetime-local",
                
                
                }),
                'to': DateTimeInput(attrs={
                   
                'type': "datetime-local",
                
                
                }),
                'description': forms.Textarea(attrs={
                    'cols': 20, 
                    'rows': 3
                }),
        }
        fields = ['name','From','to','img','location','description','tags']        

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Event Name"
        self.fields['img'].label = "Poster"
        self.fields['tags'].label = "#Tags"



class RentalForm(forms.ModelForm):
    class Meta:
        model = Post
        widgets = {
                
                'description': forms.Textarea(attrs={
                    'cols': 20, 
                    'rows': 3
                }),
        }
        fields = ['name', 'img', 'rent_option', 'currency','price_per_day','location','description','tags']
      
    
    def __init__(self, *args, **kwargs):
        super(RentalForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Rent Name"
        self.fields['price_per_day'].label ="Price per day"
        self.fields['img'].label ="Image"
        self.fields['tags'].label = "#Tags"

class ContactForm(forms.ModelForm):
    class Meta:
        model = Post
        widgets = {
                
                'description': forms.Textarea(attrs={
                    'cols': 20, 
                    'rows': 3
                }),
        }
        fields = ['name', 'contact_type','phone_number','email_id','location','img','description','tags']        

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Company/Person Name"
        self.fields['img'].label ="Image"
        self.fields['tags'].label = "#Tags"


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title']

        widgets = {
            'content': forms.Textarea(attrs={'cols': 20, 'rows': 3})
        }

blog/api/views.py
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework.response import Response

from blog.models import Post


class LikeToggleAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, pk, format=None):
        post_qs = Post.objects.get(pk=pk)
        message = "Not allowed"
        if request.user.is_authenticated:
            is_liked = Post.objects.like_toggle(request.user, post_qs)
            liked_count = post_qs.liked.all().count()
            return Response({'liked': is_liked, 'likes_count': liked_count})
        return Response({"message": message}, status=400)

blog/views.py
from .models import Post, Comment
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import PostForm,ChoicesForm,EventForm,TalentForm,ContactForm,ShowForm,RentalForm
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView
)


class PostListView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'
    paginate_by = 30

    def get_queryset(self):
        try:
            keyword = self.request.GET['q']
        except:
            keyword = ''
        if (keyword != ''):
            object_list = self.model.objects.filter(
                Q(content__icontains=keyword) | Q(title__icontains=keyword))
        else:
            object_list = self.model.objects.all()
        # print(object_list)
        return object_list

class UserPostListView(ListView):
    model = Post
    template_name = 'user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    
    template_name = 'post_detail.html'
    if Post.form_choice == '1':
        title = Post.From+" to "+Post.to
    


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    post_choice = '0'
    template_name = 'post_form.html'
    def get_form_class(self):
       post_choice = self.request.GET.get('post_select', '1')
       
       self.post_choice= post_choice
       if post_choice == '1':
        return ShowForm

       if post_choice == '2':
            return TalentForm

       if post_choice == '3':
            return EventForm   

       if post_choice == '4':
            return RentalForm

       if post_choice == '5':
            return ContactForm  



    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context['select_form'] = ChoicesForm()
        
        return context    
       
 
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.form_choice = self.post_choice
        if form.instance.form_choice == '1':
            form.instance.title = "added event from "+str(form.instance.From)+" to "+str(form.instance.to)+" in "+form.instance.location
        elif form.instance.form_choice == '4':
            form.instance.title = "posted show on "+str(form.instance.show_language)+" "+str(form.instance.genre) +" "+form.instance.show+" "+form.instance.name
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    
    model = Post
    
    # post_choice = Post.form_choice
    if Post.form_choice == '3':
        fields = ['From','to','img','location','description','tags']        

    if Post.form_choice == '1':
        fields = ['talent','language','location','img','description','tags']
    
    template_name = 'post_form.html'
    
    def form_valid(self, form):
        
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def update_post(request, pk):
    post = Post.objects.get(id=pk)
    
    post_choice = post.form_choice
    # print(post_choice)
    fields='__all__'
    if post.form_choice == '1':
        form = ShowForm(instance=post)  

    if post.form_choice == '2':
        form = TalentForm(instance=post)  
    
    if post.form_choice == '3':
        form = EventForm(instance=post)  
    
    if post.form_choice == '4':
        form = RentalForm(instance=post) 

    if post.form_choice == '5':
        form = ContactForm(instance=post) 
    
    template_name = 'post_form_update.html'    
    if request.method == 'POST':
        if post.form_choice == '1':
            form = ShowForm(request.POST, instance=post)

        if post.form_choice == '2':
            form = TalentForm(request.POST, instance=post)
        
        if post.form_choice == '3':
            form = EventForm(request.POST, instance=post)
        
        if post.form_choice == '4':
            form = RentalForm(request.POST, instance=post)

        if post.form_choice == '5':
            form = ContactForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
            return redirect('/')

    content = {'form':form, }
    return render(request,template_name,content)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'post_confirm_delete.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'about.html', {'title': 'About'})


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        user = User.objects.get(id=request.POST.get('user_id'))
        text = request.POST.get('text')
        Comment(author=user, post=post, text=text).save()
        messages.success(request, "Your comment has been added successfully.")
    else:
        return redirect('post_detail', pk=pk)
    return redirect('post_detail', pk=pk)

blog/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/index.html
{% extends "base1.html" %}
{% load static %}
{% load embed_video_tags %}
{% block content %}

            
    <!--===============================LEFT=========================--->
<div class="left">
    {% if user.is_authenticated %}
    
    <div class="profile">
        
            <div class="profile-photo">
                <img src="{{ user.profile.image.url }}" alt=""></a>
            </div>
            <div class="handle">
                <p class="text-muted">
                    <a href="/profile"> @{{ user.profile.user }}  </a>
                    
                </p>
                
            </div>
       
        
        
    </div>
    
   
    <hr>
    


        <!------------------------SIDEBAR---------------------------------->
        <div class="sidebar">
        <a href="/" class="menu-item active" >
            <span><i class="uil uil-home"></i></span><h3>Home</h3>
        </a>
        <a href="/profile" class="menu-item" id="notifications" >
            <span><i class="uil uil-bell"></i></span><h3>Profile</h3>
        </a>
        
        <a href="/logout" class="menu-item" >
            <span><i class="uil uil-sign-out-alt"></i></span><h3>Logout</h3>
        </a>
        
        </div>
        {% else %}
        <div class="sidebar">
            <a href="/" class="menu-item active" >
                <span><i class="uil uil-home"></i></span><h3>Home</h3>
            </a>
            <a href="/login" class="menu-item" >
                <span><i class="uil uil-signin"></i></span><h3>Login</h3>
            </a>
        </div>

    {% endif %}
        <!---------------------END OF SIDEBAR----------------------->
        <!-- <label for="create-post" class="btn btn-primary">Create Post</label> -->
</div>
<!---------------------END OF LEFT----------------------->
    <!--===============================MIDDLE=========================--->
<div class="middle">
    
        <!----------------------------FEEDS---------------->
        <div class="feeds">
            <!----------------------------FEED 1---------------->
            {% for post in posts %}
            <div class="feed">
                <div class="head">
                    <div class="user">
                        <a class="profile">
                            <div class="profile-photo">
                                
                                <img src="{{ post.author.profile.image.url }}" >
                            </div>
                          </a>

                        <div class="ingo">
                            <a href="{% url 'user_posts' post.author.username %}"><h7>{{ post.author }} </h7></a>
                            <small>{{post.title}}</small>
                            <br>
                            <small>{{ post.date_posted|date:"F d, Y" }} </small>

                        </div>
                    </div>
                    <span class="edit">
                        <a href="{% url 'post_detail' post.pk %}"><i class="uil uil-ellipsis-h"></i></a></p>
                    </span>
                </div>
                
                
                <div class="photo">

                    

                    <div class="video-container">
                        {% video post.video_link as my_video %}
                
                            {% if my_video.url %}
                                
                                {% if post.img %}
                                
                                    <img src="{{post.img.url}}" >

                                {% else %}
                                    <img src="{{ my_video.thumbnail }}" alt="My Awesome Video">
                                {% endif %}
                                
                                    
                                 
                                <div class="overlay">
                                
                                    <a href="{% url 'post_detail' post.pk %}" class="icon" title="User Profile">
                                        <!-- <i class="fa fa-youtube-play" style="font-size:48px;color:red"></i> -->
                                        <!-- <i class="fa fa-youtube-play" style="font-size:100px"></i> -->
                                        <i class="fa fa-play" style="font-size:48px;color:rgba(223, 237, 250, 0.5)"></i>
                                        <!-- <i class="bi bi-play"></i> -->
                                    </a>
                                </div>
                            {% endif %}
               
                        {% endvideo %}

                    
                    </div>

                

                    <!-- <h1>{{post.image}}</h1> -->
                    
                
                        
                        {% if not '1' == post.form_choice %}
                       
                            {% if post.img %}
                            
                                <a href="{% url 'post_detail' post.pk %}"><img src="{{post.img.url}}" ></a>
                                


                            {% endif %}
                                    
                        {% endif %}
                    
                                
                

                </div>
                <!-- <div class="action-buttons">
                    <div class="interaction-buttons">
                        <span><i class="uil uil-heart"></i></span>
                        <span><i class="uil uil-comment-dots"></i></span>
                        <span><i class="uil uil-share"></i></span>
                    </div>
                    <div class="bookmark">
                        <span><i class="uil uil-bookmark"></i></span>
                    </div>
                </div>
                <div class="liked-by">
                    <span><img src="./images/profile-10.jpg" alt=""></span>
                    <span><img src="./images/profile-17.jpg" alt=""></span>
                    <span><img src="./images/profile-20.jpg" alt=""></span>
                    <p>Liked by <b>Prakash</b> and <b>2,345 others</b></p>
                </div> -->

                <div class="caption">
                    <p >{{ post.description|truncatechars_html:200 }} {{ post.tags|truncatechars_html:100 }}  <a href="{% url 'post_detail' post.pk %}">more</a></p>
                </div>
                <!-- <div class="comments text-muted">View all 122 comments</div> -->
                
                {% if post.liked.count %}
                    <p id="likes_count" style="color: rgb(37, 37, 37)">{{post.liked.count}} liked</p>
                {% endif %}
            </div>


            {% endfor %}
            <!----------------END OF FEED ------------------>
            {% if is_paginated %}
            {% if page_obj.has_previous %}
              <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
              <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
      
            {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% endif %}
            {% endfor %}
      
            {% if page_obj.has_next %}
              <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
              <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
          {% endif %}
            

        </div>

        <!----------------============ END OF FEEDS =========------------------>
    
</div>
    <!--===============================RIGHT=========================--->
<div class="right">
    
    <div class="messages">
        
            <div class="heading">
                <h4>Filter catagory</h4>
            </div>
            <!-------------------Search bar ---------------->
            <div class="search-bar">
                <!-- <i class="uil uil-search"></i> -->
                <input type="search" placeholder="Search Post" id="message-search">
            </div>
            <!-------------------MESSAGES CATEGORY ---------------->
            <div class="category">
                
            </div>
        </div>

        
</div>

{% endblock content %}

blog/templates/post_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

            
<!--===============================LEFT=========================--->
<div class="left">
    
</div>
<!---------------------END OF LEFT----------------------->
    <!--===============================MIDDLE=========================--->
<div class="middle">
    
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post_detail' object.id %}">Cancel</a>
            </div> 
        </form>
    </div>
    
</div>
    <!--===============================RIGHT=========================--->
<div class="right">
    
    

        
</div>

{% endblock content %}

blog/templates/post_form.html
{% extends "base1.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

            
<!--===============================LEFT=========================--->
<div class="left">
    
</div>
<!---------------------END OF LEFT----------------------->
    <!--===============================MIDDLE=========================--->
<div class="middle">
    
    <div class="content-section">
        <form id="select_form" method="GET">
            {{ select_form|crispy }}
            <div class="btn-group btn-group-justified" role="group">
              <!-- <div class="btn-group" role="group">
                <button class="btn btn-primary" type="submit">Select</button>
              </div> -->
            </div>

            
          </form>

          <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            <fieldset class="form-group" >
                <legend class="border-bottom mb-4">Create Post</legend>
                
                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
        
    </div>
    <!-- Medium Editor -->
    <script>var editor = new MediumEditor('.editable');</script>
    
</div>
    <!--===============================RIGHT=========================--->
<div class="right">
    

        
</div>

{% endblock content %}
{% block javascript %}
<script>
$('#id_post_select').on('change', function(){
    $(this).closest('form').submit();
});
</script>
{% endblock javascript %}

blog/templates/post_form_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

            
<!--===============================LEFT=========================--->
<div class="left">
    
</div>
<!---------------------END OF LEFT----------------------->
    <!--===============================MIDDLE=========================--->
<div class="middle">
    
    <div class="content-section">
        

          <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            <fieldset class="form-group" >
                <legend class="border-bottom mb-4">Update</legend>
                
                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
        
    </div>
    <!-- Medium Editor -->
    <script>var editor = new MediumEditor('.editable');</script>
    
</div>
    <!--===============================RIGHT=========================--->
<div class="right">
    

        
</div>

{% endblock content %}
{% block javascript %}
<script>
$('#id_post_select').on('change', function(){
    $(this).closest('form').submit();
});
</script>
{% endblock javascript %}